### ISSUE TITLE
General Issue: Content for Release 0.8.0

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiral#1211]
### Background Information

Hi all,

We need to decide upon enhancements, updates, vignettes, scripts that we would like to see go into `admiral 0.8.0`

- [ ] Lab Grading Function
- [ ] Framingham Function
- [ ] admh script - https://github.com/pharmaverse/admiral/issues/502
- [ ] adlbhy script - https://github.com/pharmaverse/admiral/issues/1041
- [ ] Vignette for merge functions
- [ ] adnca script?
- [ ] adqs script
- [ ] Remove admiral_adamdata to separate package
- [ ] partial dates refactor - https://github.com/pharmaverse/admiral/issues/879 & see proposal at https://exbpbox.ent.box.com/file/958836772299
- [x] package extensions guidance/repo template - https://github.com/pharmaverse/admiral/issues/949
- [ ] training materials – internal issue for Roche which @koegerr will share once available to see if useful to open up
- [ ] {admiral.test} clean up and clearer process on how to extend datasets 
- [ ]  admiral.test  needs specs files in line with our updates for the e2e vignette - 
- [ ] Make reference page more readable - #1105 

What else would we like to see included in this update?  

Once we can decide upon what to include, then I think we can start thinking about a date for the next release.  Or if we are trying to time with another package(s) then make an informed choice about what we want included.

@pharmaverse/admiral 

### Definition of Done

Decide on what we want to go into admiral 0.8.0

**Comment by rossfarrugia** [comment]
Sharing summary of ideas from last sponsor/leads call:

- partial dates refactor - https://github.com/pharmaverse/admiral/issues/879 & see proposal at https://exbpbox.ent.box.com/file/958836772299
- package extensions guidance/repo template - https://github.com/pharmaverse/admiral/issues/949
- training materials – internal issue for Roche which @koegerr will share once available to see if useful to open up
- ADMH - https://github.com/pharmaverse/admiral/issues/502
- Hy's Law - https://github.com/pharmaverse/admiral/issues/1041
- {admiral.test} clean up and clearer process on how to extend and needs specs files in line with our updates for the e2e vignette - plus MH needs some extra vars - https://github.com/pharmaverse/admiral.test/issues/53 & https://github.com/pharmaverse/admiral.test/issues/51 & https://github.com/pharmaverse/admiral.test/issues/54

**Comment by bundfussr** [comment]
@rossfarrugia , I have added two comments to the imputation document in box.

**Comment by rossfarrugia** [comment]
i would also add https://github.com/pharmaverse/admiral/issues/1105 to the priority list for next release

**Comment by bms63** [comment]
I have added two comments as well to the box document.

**Comment by bms63** [comment]
@pharmaverse/admiral Any other priorities we would like to see included in this v8 release?

**Comment by bms63** [comment]
All this stuff is being tracked so closing it out.
