### ISSUE TITLE
General Issue: Tracking updates for admiraldev

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiral#2372]
### Background Information

admiraldev is updating assertion functions around better messaging.  This issue is to help understand and fix any problems that arise from the upstream updates.

* https://github.com/pharmaverse/admiraldev/issues/367

### Definition of Done

- [x] Place Remotes into DESCRIPTION
- [x] Document impacted functions in Developer Notes (if feasible)
- [x] Update impacted functions
- [ ] Investigate examples, vignettes, templates where impacted
- [ ] Profit

### Issues completed around this update to admiraldev
* https://github.com/pharmaverse/admiral/issues/2375
* https://github.com/pharmaverse/admiral/issues/2382
* Minor update done here: https://github.com/pharmaverse/admiral/pull/2393
* Minor update done here: https://github.com/pharmaverse/admiral/pull/2397
* https://github.com/pharmaverse/admiral/issues/2406
* https://github.com/pharmaverse/admiral/issues/2404
* https://github.com/pharmaverse/admiral/issues/2403
* https://github.com/pharmaverse/admiraldev/pull/450

**Comment by bms63** [comment]
Hi @pharmaverse/admiral
