### ISSUE TITLE
Update all vignettes as per best practices

### ISSUE THREAD

**Issue by kabis-ops** [pharmaverse/admiral#572]
Review/update all vignettes as per recommendations in "Writing vignettes". Consider also the update to the "Writing Vignettes" vignette defined in https://github.com/Roche-GSK/admiral/issues/605.

- [x] vignettes/admiral.Rmd (Eric)
- [x] vignettes/adsl.Rmd (Samia)
- [x] vignettes/bds_exposure.Rmd (Samia)
- [x] vignettes/bds_finding.Rmd (Gordon)
- [x] vignettes/faq.Rmd (Eric)
- [x] vignettes/git_usage.Rmd (Ben)
- [x] vignettes/imputation.Rmd (Stefan)
- [x] vignettes/occds.Rmd (Gordon)
- [x] vignettes/programming_strategy.Rmd (Eric)

**Comment by esimms999-gsk** [comment]
faq.Rmd - questions:
- "admiral does not provide a link to an explicit specification in the define.xml." - is this a note so that people do not assume there will be something in the define.xml?
- " ... a Github repo would be needed for each company - our request of companies using admiral would be to also keep these open source as we will do with the Roche & GSK versions, as this transparency could help us identify modules that are better moved up to the core package." One of the reasons we looked at company-specific was due to passwords for accessing databases (e.g. Stefan with SMQ) and we did not want to leave the code visible to others.

**Comment by millerg23** [comment]
Hi @kabis-ops
Apologies for late response. In the script we add the ADSL vars after the initial creation of EXDOSE and EXADJ (and adding on SUPP). We also store the ADSL vars in a vector.
```
 # Get list of ADSL vars required for derivations
adsl_vars <- vars(TRTSDT, TRTSDTM, TRTEDTM)

# Part 1
# Join ADSL with ex and derive required dates, variables
adex0 <- ex %>%
  # Join ADSL with EX (only ADSL vars required for derivations)
  left_join(
    adsl %>% select(STUDYID, USUBJID, !!!adsl_vars),
    by = c("STUDYID", "USUBJID")
  ) %>%
```

Then at the end add all other ADSL vars:
```
# Join all ADSL with EX
adex <- adex %>%

  left_join(select(adsl, !!!admiral:::negate_vars(adsl_vars)),
            by = c("STUDYID", "USUBJID")
  )
```

Only other thing I see is ASEQ is slightly different, in script its:
```
# Calculate ASEQ
  derive_obs_number(
    new_var = ASEQ,
    by_vars = vars(STUDYID, USUBJID),
    order = vars(PARCAT1, ASTDT, VISIT, VISITNUM, EXSEQ, PARAMN),
    check_type = "error"
  )
```
I don't think this really matters.

**Comment by esimms999-gsk** [comment]
Still to be fixed in programming_strategy.Rmd: Lines 86, 87, 393 : "(link to remove function)", "(lnk to check function)",  "(link to be added)" - need links.

**Comment by bundfussr** [comment]
I have created #671 for the remove and the check function.

**Comment by thomas-neitmann** [comment]
@esimms999-gsk What's the status of the programming strategy doc update?

**Comment by esimms999-gsk** [comment]
@thomas-neitmann 
programming_strategy.Rmd:

- **Input, Output and Side-effects:** two points about temporary variables need links or re-wording: "link to remove function" and "link to check function"
- **Input Checking:** link to "assertions" - how can I test this link works?
- **Unit Testing:** link to "Writing Unit Tests in {admiral}" - how can I test this link works?
- I do not see programming_strategy.Rmd mentioned in the pkgdown.yml file. Note that writing_vignettes.Rmd mentions this must be done in the _pkgdown.Rmd file (with leading underscore): I have opened a separate issue asking if the name should have that leading underscore.

**Comment by thomas-neitmann** [comment]
Thanks @esimms999-gsk! Could you take care of editing these findings and open a new pull request? To check the links please try them on our [website](https://pharmaverse.github.io/admiral/index.html).

**Comment by esimms999-gsk** [comment]
@thomas-neitmann 
programming_strategy.Rmd:
**Input Checking:** link to assertions - this is good.
**Unit Testing:** link to "Writing Unit Tests in {admiral}" - the web page does not have this link so I cannot test it.
I was looking in the wrong place wrt pkgdown.yml (I was looking at /admiral/.github/workflows/pkgdown.yml). Ben pointed me to the correct place (/admiral/_pkgdown.yml) and programming_strategy has been added.

I attempted branch/PR for remainder simple changes, but think I did it wrong. :( Please see 572_programming _strategy branch.
